### PR TITLE
Merge `v1.6.2` into `master`

### PR DESCRIPTION
**Pull request by Ocramius**
This patch still happens to contain artifacts due to rebases that happened before we discussed our merge-up strategy for `doctrine/*` repositories. Unsure if we should merge manually, or if we should defer this strategy until after `1.7.0` is released.

### CODE REVIEW

**Comment by ostrolucky** [comment]
there are still some merge conflicts

**Comment by Ocramius** [comment]
W00t, wait, this is wrong :|

**Comment by Ocramius** [comment]
> Merge branch 'master' into 1.6

is github drunk? :|

**Comment by Ocramius** [comment]
Nope, this is just github's way to resolve conflicts: I'll have to do a hard reset of `1.6` then, sorry :(

**Comment by Ocramius** [comment]
`1.6` was reset to 09deece2d570b8290e55707c7d9eaddd315b4379

**Comment by Ocramius** [comment]
Hmm, I thought this was already merged? :|

**Comment by ostrolucky** [comment]
I don't think creating PRs for these branch merges will work when there are conflicts. I think this needs to be merged manually and resolve conflict during that.

**Comment by Ocramius** [comment]
Yeah, the automated releases tool we wrote creates an intermediate branch where these issues can be solved

**Comment by greg0ire** [comment]
The conflict looks funny:

```
 <<<<<<< HEAD                                                                                                                                                                                                 
This release, combined with the release of [`doctrine/annotations` `v1.6.1`](https://github.com/doctrine/annotations/releases/tag/v1.6.1),                                                                   
=======                                                                                                                                                                                                      
This release, combined with the release of [`doctrine/collections` `v1.6.1`](https://github.com/doctrine/collections/releases/tag/v1.6.1),                                                                   
>>>>>>> origin/1.6
```

I think the correct version is the master one.

**Comment by greg0ire** [comment]
If you approve #214 , I might be able to push the result to master (no merge commit)

**Comment by greg0ire** [comment]
> Pull request successfully merged and closed
> You’re all set—the 1.6 branch can be safely deleted. 

No thanks, I'm good!

**Comment by alcaeus** [comment]
Enabled branch protection for all `1.*` branches since I almost clicked that button myself. Let me know if there are issues.

**Pull request closed without merging**
