### PR TITLE
Removes support for PHP 5.x

### PR DESCRIPTION
**Pull request by railto**
Removes support for PHP 5.x from composer.json and .travis.yml

### CODE REVIEW

**Comment by railto** [comment]
Closing as I do not have the ability to get this to pass

**Comment by Ocramius** [comment]
Reopening: still needs to happen, even if you don't work on the PR yourself.

**Comment by mikeSimonson** [comment]
@Ocramius php 7 only ?

**Comment by Ocramius** [comment]
@mikeSimonson 7.0+

**Comment by Ocramius** [comment]
@mikeSimonson reopening since you didn't bump composer requirements

**Comment by mikeSimonson** [comment]
@Ocramius Sorry it's fixed.

**Comment by Ocramius** [comment]
@mikeSimonson that's the only reason why this wasn't merged yet, see https://travis-ci.org/doctrine/collections/jobs/198663385

**Comment by lcobucci** [comment]
Processed in #107

**Pull request closed without merging**
