### PR TITLE
Change Collection#slice return type to Collection

### LINKED ISSUE #195: slice() method should return a Collection instead of an array
See question here where this was originally requested https://github.com/doctrine/collections/pull/125#issuecomment-378990965

### PR DESCRIPTION
**Pull request by LIQRGV**
This commit should resolve #195

### CODE REVIEW

**Comment by LIQRGV** [comment]
Duplicate of #196

**Comment by stof** [comment]
This is a BC break, so it cannot be done

**Comment by SenseException** [comment]
@stof That's why 2.0 is the target branch, but I assume that there are no plans to make a collection return a new collection instance?

**Comment by stof** [comment]
@SenseException this still looks like a BC break for which it is impossible to provide a smooth migration path, which makes it a very hard BC break for the ecosystem.

**Comment by greg0ire** [comment]
Closing as per https://github.com/doctrine/collections/pull/264#issuecomment-1072345923

**Pull request closed without merging**
