### PR TITLE
Comparison startsWith, endsWith

### PR DESCRIPTION
**Pull request by pine3ree**
Trying to propose again a couple of common comparison test (related to contains test).
I also have the related PR for doctrine2 repo ready.

### CODE REVIEW

**Comment by beberlei** [comment]
For reference, we have contains already, which does a string match on any part of the string.

**Comment by mikeSimonson** [comment]
@beberlei This seems good to go to me.

**Comment by mikeSimonson** [comment]
merged in https://github.com/doctrine/collections/pull/78

**Comment by stof** [comment]
Have you sent a PR updating the ORM to support these new operators ?

**Comment by mikeSimonson** [comment]
@stof Against what code that PR need to be made ?

**Comment by stof** [comment]
@mikeSimonson the ORM code turning expression into SQL queries for usage in persistent collections: https://github.com/doctrine/doctrine2/blob/c1943624ab1260c629316bab104dc5130c060154/lib/Doctrine/ORM/Persisters/SqlExpressionVisitor.php

**Comment by mikeSimonson** [comment]
Those are not compositeExpression but comparison ( the method above this one).
It doesn't look like any change is needed there but maybe there https://github.com/doctrine/doctrine2/blob/c1943624ab1260c629316bab104dc5130c060154/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php#L99 ?

**Comment by stof** [comment]
hmm yeah, I forgot that the SqlExpressionVisitor actually delegates to each persister to build the comparison.

**Comment by grizzm0** [comment]
Any ETA on the ORM support? ;)

I'm not that into the ORM source. Would it be enough to just add them to the comparisonMap?

**Comment by Ocramius** [comment]
@grizzm0 nobody made a patch for this, as far as I know. `SqlExpressionVisitor` is where you want to start :-)

**Comment by grizzm0** [comment]
@Ocramius Probably deeper than my understanding of the ORM. :/

**Pull request closed without merging**
