### PR TITLE
Add check in ClosureExpressionVisitor to use literal public method if available

### PR DESCRIPTION
**Pull request by rikbruil**
The PR belonging to #134.

I'm not sure if there was a reason not to check for existence of a method with the literal passed field name. If not, this PR adds this check ;)

### CODE REVIEW

**Comment by Majkl578** [comment]
Internal note: We should consider using naming strategy provided from outside rather than trying to guess method name convention.

**Comment by albertboada** [comment]
👍

**Comment by jwage** [comment]
Seems okay to me.

**Comment by Ocramius** [comment]
Closing as `won't fix` and `bc break` for reasons matching the ones I've explained in #149

**Pull request closed without merging**
