### PR TITLE
Late Static Binding for the ClosureExpressionVisitor

### PR DESCRIPTION
**Pull request by martixy**
Makes the class easier to inherit from.

### CODE REVIEW

**Comment by Ocramius** [comment]
This class is not designed for inheritance: closing as `invalid`.

**Comment by Ocramius** [comment]
> Why not?

BC (backwards compatibility) and maintenance boundaries, mostly. The class you want to extend is `ExpressionVisitor`, not `ClosureExpressionVisitor`.

The mistake is on our end, for not marking `ClosureExpressionVisitor` `final` in first place (and we can't do that now), sorry.

**Comment by martixy** [comment]
The functionality is generic enough to be usable outside doctrine, and reimplementing the whole class seems pointless.

But since I can't do anything I guess I'll settle for copy-pasting it for my purposes.

**Comment by Ocramius** [comment]
> But since I can't do anything I guess I'll settle for copy-pasting it for my purposes.

Please remember to also copy the related unit tests to prevent regressions due to inheritance changes.

**Pull request closed without merging**
