### PR TITLE
Use PSR-4

### PR DESCRIPTION
**Pull request by Nyholm**
Sorry for bothering this super stable package. May I ask to consider to update to PSR-4?

Im using https://github.com/humbug/php-scoper which automatically rewrites the namespace before Im building a PHAR.

### CODE REVIEW

**Comment by Ocramius** [comment]
LGTM :+1:

**Comment by Nyholm** [comment]
Thank you merging

**Comment by greg0ire** [comment]
I think this should have been done on 1.5, and the depth of the tree shouldn't have been preserved. See  https://github.com/doctrine/collections/pull/138/files

**Comment by Ocramius** [comment]
Depth of tree is correctly preserved, as the doctrine organisation does not
endorse PSR-4 namespace prefixes and still suggests for the sake of tooling
simplicity to use PSR-0 path mappings.

**Pull request merged**
