### PR TITLE
Require PHP 7.1

### PR DESCRIPTION
**Pull request by lcobucci**
Related to https://github.com/doctrine/doctrine2/issues/6425

### CODE REVIEW

**Comment by malukenho** [comment]
@lcobucci how about `declare(strict_types=1);`?

**Comment by lcobucci** [comment]
@malukenho I like the idea but I rather add it on the major release (along with the type-hints everywhere)...

**Comment by Ocramius** [comment]
Strict types can indeed only be added later in a major version. Checking just the current diff, some upcasts may happen for asc/desc ordering, and that means that it would crash hard on people not strictly passing strings to the API.

**Comment by Ocramius** [comment]
: shipit:

**Comment by Majkl578** [comment]
FYI: See #125 for strict types, etc. 😎

**Pull request merged**
