### PR TITLE
Admit no prefix as getter

### PR DESCRIPTION
**Pull request by jorge-ruukfy**
As an alternative to reflection or closure hacking to properly get the private property whenever not using `getXXX()` `isXXX()` accessors,
just added blank prefix '' to call DDD oriented notation (ex. `id()` )

Is adverted to who want to use this in a future, that if the method returns a valueObject, to use ::CONTAINS operator that casts to string, although the VO must be stringable

### CODE REVIEW

**Comment by SenseException** [comment]
Interesting addition prevent classic getter names. Can you please also extend the tests for this naming?

**Comment by SenseException** [comment]
Please fix the issues listed in the coding standards results of the build.

**Comment by SenseException** [comment]
Looks great. Please adapt your 2 last commit message as described in our contribution guideline. https://www.doctrine-project.org/contribute/index.html#working-on-topic-branches

**Comment by jorge-ruukfy** [comment]
@SenseException :tada:

**Review by SenseException — DISMISSED** [review]

**Comment by derrabus** [comment]
Do we consider this to be a bugfix? Otherwise, we should target 1.7.x, shouldn't we?

**Comment by SenseException** [comment]
You're right. This is a feature.

**Review by derrabus — APPROVED** [review]

**Pull request merged**
