### PR TITLE
Made initialized protected for extensibility.

### PR DESCRIPTION
**Pull request by guilhermeblanco**
I'm working on making PersistentCollection extends AbstractLazyCollection and it is required to have access to initialized property. This PR allows that.

### CODE REVIEW

**Comment by stof** [comment]
should it be protected, or should it have only a protected getter to ensure that mutating it is done only in initialize ?

**Comment by Ocramius** [comment]
I'd rather have a getter here, so that we can refactor later on. This also allows composition rather than forcing direct inheritance.

Yes, I know it's an abstract type.

**Comment by beberlei** [comment]
For performance reasons i prefer the `protected` variable instead of a getter tbh.

**Comment by guilhermeblanco** [comment]
@Ocramius we already a getter `isInitialized()`. I'd require a setter.
PersistentCollection in ORM calls initialized around 10 times, which I'd prefer to have as protected instead of a method for performance reasons too.

**Comment by fprochazka** [comment]
Entity might have it's own `$initialized` property. This would break it imho.

**Pull request merged**
