### PR TITLE
Enables automatic serialization with json_encode native function

### PR DESCRIPTION
**Pull request by hectorprats**
with this feature, we can now use \json_encode with our Collections.

Before, \json_encode returns null. Now we receive a good response

### CODE REVIEW

**Comment by hectorprats** [comment]
done!

**Comment by hectorprats** [comment]
up!, please, review. Is usefull

**Comment by hectorprats** [comment]
How can it open the door to worms if it is native PHP code? It is easier for JMSSerializer to make errors than the native PHP code.

**Comment by Ocramius** [comment]
Closing as `won't fix` here: `Collection` is an in-memory representation, and should most likely stay as such.

Also, there is no guarantee that a `Collection` is serializable, as its API allows for containing a `mixed[]`.

Conversion to another format should be done by any mapper (as suggested above, JMSSerializer and the likes) calling `->toArray()` on it.

**Pull request closed without merging**
