### PR TITLE
Bump PHPStan level

### PR DESCRIPTION
**Pull request by derrabus**
This PR bumps the PHPStan level to 8 and fixes some issues found on the way.

### CODE REVIEW

**Review by greg0ire — COMMENTED** [review]
I noticed that you switched to tabs on the `doctrine/persistence` PR but not on this one, is it deliberate?

**Review by greg0ire — APPROVED** [review]
Ah actually it was just for the baseline. This should be fine.

**Comment by greg0ire** [comment]
Thanks @derrabus !

**Comment by derrabus** [comment]
> I noticed that you switched to tabs on the `doctrine/persistence` PR but not on this one, is it deliberate?

I have let PHPStan regenerate the baseline. I don't think we should edit that file manually.

**Pull request merged**
